package org.example;

import java.util.Map;
import java.util.Optional;
import java.util.TreeMap;
import java.util.HashMap;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Controller;
import org.springframework.web.client.RestTemplate;
import org.springframework.web.bind.annotation.*;

@Controller	// This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
	@Autowired // This means to get the bean called userRepository
			   // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;

	@Autowired
	private DataWarehouseRepository dataWarehouseRepository;

	@Autowired
	private ProductRepository productRepository;

	@Autowired
	private PurchaseRepository purchaseRepository;

	@Value("${llm.url:http://localhost:11434/api/generate}")
	private String llmUrl;

	@Value("${llm.model:llama3.2}")
	private String llmModel;

	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewUser (@RequestParam String name
			, @RequestParam String email) {

		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		User n = new User();
		n.setName(name);
		n.setEmail(email);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}

	@GetMapping(path="/warehouses")
	public @ResponseBody Iterable<DataWarehouse> getAllWarehouses() {
		return dataWarehouseRepository.findAll();
	}

	@GetMapping(path="/warehouses/{warehouseID}")
	public @ResponseBody DataWarehouse getOneWarehouse(@PathVariable("warehouseID") String warehouseID) {
		Optional<DataWarehouse> warehouse = dataWarehouseRepository.findById(warehouseID);
		if (warehouse.isPresent()) {
			return warehouse.get();
		}
		return null;
	}

	@GetMapping(path="/warehouses/{warehouseID}/products")
	public @ResponseBody Iterable<Product> getProductsOfWarehouse(@PathVariable("warehouseID") String warehouseID) {
		return productRepository.findByWarehouseWarehouseID(warehouseID);
	}

	@GetMapping(path="/warehouses/{warehouseID}/products/{productID}")
	public @ResponseBody Product getOneProductOfWarehouse(@PathVariable("warehouseID") String warehouseID,
			@PathVariable("productID") String productID) {
		Optional<Product> product = productRepository.findByWarehouseWarehouseIDAndProductID(warehouseID, productID);
		if (product.isPresent()) {
			return product.get();
		}
		return null;
	}

	@PutMapping(path="/warehouses/{warehouseID}")
	public @ResponseBody String updateWarehouse(@PathVariable("warehouseID") String warehouseID,
			@RequestParam(required = false) String warehouseName,
			@RequestParam(required = false) String warehouseAddress,
			@RequestParam(required = false) String warehousePostalCode,
			@RequestParam(required = false) String warehouseCity,
			@RequestParam(required = false) String warehouseCountry) {
		Optional<DataWarehouse> warehouse = dataWarehouseRepository.findById(warehouseID);
		if (!warehouse.isPresent()) {
			return "Warehouse not found";
		}

		DataWarehouse dataWarehouse = warehouse.get();
		if (warehouseName != null) {
			dataWarehouse.setWarehouseName(warehouseName);
		}
		if (warehouseAddress != null) {
			dataWarehouse.setWarehouseAddress(warehouseAddress);
		}
		if (warehousePostalCode != null) {
			dataWarehouse.setWarehousePostalCode(warehousePostalCode);
		}
		if (warehouseCity != null) {
			dataWarehouse.setWarehouseCity(warehouseCity);
		}
		if (warehouseCountry != null) {
			dataWarehouse.setWarehouseCountry(warehouseCountry);
		}

		dataWarehouseRepository.save(dataWarehouse);
		return "Updated";
	}

	@GetMapping(path="/products")
	public @ResponseBody Iterable<Product> getAllProducts() {
		return productRepository.findAll();
	}

	@GetMapping(path="/purchases")
	public @ResponseBody Iterable<Purchase> getAllPurchases() {
		return purchaseRepository.findAll();
	}

	@GetMapping(path="/warehouses/{warehouseID}/purchases")
	public @ResponseBody Iterable<Purchase> getPurchasesOfWarehouse(@PathVariable("warehouseID") String warehouseID) {
		return purchaseRepository.findByWarehouseWarehouseID(warehouseID);
	}

	@GetMapping(path="/sales-preview")
	public @ResponseBody String getSalesPreview() {
		Map<String, Integer> sums = new TreeMap<>();
		for (Purchase purchase : purchaseRepository.findAll()) {
			String key = purchase.getWarehouse().getWarehouseID() + " "
					+ purchase.getWarehouse().getWarehouseName() + " / "
					+ purchase.getProduct().getProductID() + " "
					+ purchase.getProduct().getProductName();
			Integer oldAmount = sums.get(key);
			if (oldAmount == null) {
				oldAmount = 0;
			}
			sums.put(key, oldAmount + purchase.getAmount());
		}

		StringBuilder prompt = new StringBuilder();
		prompt.append("Create a short sales preview for the next three months. ");
		prompt.append("Use these sold amounts from the warehouse project:\n");
		for (Map.Entry<String, Integer> entry : sums.entrySet()) {
			prompt.append(entry.getKey()).append(": ").append(entry.getValue()).append("\n");
		}
		prompt.append("Answer in simple English and list each warehouse and product.");

		HashMap<String, Object> body = new HashMap<>();
		body.put("model", llmModel);
		body.put("prompt", prompt.toString());
		body.put("stream", false);

		try {
			RestTemplate restTemplate = new RestTemplate();
			Map response = restTemplate.postForObject(llmUrl, body, Map.class);
			if (response != null && response.get("response") != null) {
				return response.get("response").toString();
			}
			return "The LLM answered, but the response was empty.";
		} catch (Exception e) {
			return "Could not call the LLM. Start Ollama or change llm.url and llm.model in application.properties.";
		}
	}
}
